#debug: true

server:
  port: ${PORT:2222}

spring:
  application:
    name: reservation-service
    
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server # should come from environment
    gateway:
      rsocket:
        client:
          service-name: reservation-service
          route-id: 400
          tags: # additional service metadata (similar to Eureka metadata tags)
            instance_name: reservation-service-1
            version: 1.0-RELEASE # version indicates that this is a release version instance (not a canary one).
          broker: # where to find the gateway RSocket broker
            ws-uri: http://localhost:7002/rsocketGateway
            connection-type: websocket    
                
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      # Logging Levels:
logging:
  level: 
    com.netflix: INFO # Overriding centrally managed log levels for this particular service..

# Actuator Endpoint Configurations
info: # /actuator/info
  app:
    description: "A service to place and review reservations."
    
      