---
spring:
  application:
    name: service-registry-client

server:
  port: ${random.int(8100,8200)}

eureka:
  instance:
    # Request a lease with a validity of 5 seconds. If until then the
    # lease has not been renewed, it expires and the Eureka server can evict it.
    # Default: 90s
    lease-expiration-duration-in-seconds: 5

    # The cadence of lease renewal, i.e. how often a heartbeat is sent to Eureka server.
    # In this case every 2 seconds. Use this only for development / debugging. In production use the ... 
    # Default: 30s
    lease-renewal-interval-in-seconds:    2

    # Instance information, URLs registered in Eureka.
    homePageUrl:          https://${vcap.application.uris[0]:localhost}/
    statusPageUrl:        https://${vcap.application.uris[0]:localhost}/actuator/info 
    healthCheckUrl:       https://${vcap.application.uris[0]:localhost}/actuator/health
    secureHealthCheckUrl: https://${vcap.application.uris[0]:localhost}/actuator/health
    hostname:             ${vcap.application.uris[0]:localhost}
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Expose all actuator / management endpoints. Don't use this in production.
management.endpoints.web.exposure.include: "*"

# Expose all health information, also from Hystrix, Eureka and others.
# See: https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#production-ready-health 
management.endpoint.health.show-details: always

---
spring.profiles: cloud

server:
  port: ${PORT:0}

eureka:
  client: 
    serviceUrl:
      defaultZone: ${eureka-server-url}   # URL as given in manifest.yml environment variable eureka-server-url.
  instance: 
    # Use proper default of 30 seconds in production.
    lease-renewal-interval-in-seconds: 30
    # Disable non-secure port in CF
    nonSecurePortEnabled: false
    # Enable secure port (https)
    securePortEnabled:    true
    # Use standard HTTPS port
    securePort:           443


