#debug: true

server:
  port: ${PORT:9999}


# Actuator Endpoint Configurations
info: # /actuator/info
  app:
    description: "A service that acts as a client to reservation-service."

spring:
  application:
    name: reservation-service-client

  cloud:
    gateway:
      rsocket:
        client:
          service-name: reservation-service-client
          route-id: 500
          tags: # additional service metadata (similar to Eureka metadata tags)
            instance_name: reservation-service-client-1
            version: 1.0-RELEASE # version indicates that this is a release version instance.
          broker: # where to find the gateway RSocket broker
            host: localhost # TODO: inject from environment for Cloud deployments.
            port: 7002      # TODO: connect via websocket, not TCP.
          forwarding:       # Routing / forwarding hints to the Gateway broker.
            "[create.reservation.{vrsn}]":     # for routes pointed at "create.reservation.{version}" (note the fugly syntax, see: https://github.com/spring-cloud-incubator/spring-cloud-rsocket/issues/1) ...
              service_name: reservation-service   # ... route the request to an instance of "reservation-service" ...
              version:      "{vrsn}-RELEASE"      # ... whose "version" is 1.0-RELEASE. Note, that this can be used for 
                                                  # canary routing, if changed to 1.0-CANARY!

